name: Jest Automated Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Set-up Node 16.x environment
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      - name: npm install
        run: npm ci
      - name: Run automated tests
        run: npm test